blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/badhope/badhope.github.io/discussions
    about: Ask questions and discuss with other community members
  - name: 📖 Documentation
    url: https://github.com/badhope/badhope.github.io#-documentation
    about: Check the documentation before opening an issue
